//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evado.UniForm.AdminClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EuLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EuLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evado.UniForm.AdminClient.EuLabels", typeof(EuLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1:.
        /// </summary>
        internal static string Address_Field_Address_1_Label {
            get {
                return ResourceManager.GetString("Address_Field_Address_1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2:.
        /// </summary>
        internal static string Address_Field_Address_2_Label {
            get {
                return ResourceManager.GetString("Address_Field_Address_2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City: .
        /// </summary>
        internal static string Address_Field_City_Label {
            get {
                return ResourceManager.GetString("Address_Field_City_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country: .
        /// </summary>
        internal static string Address_Field_Country_Label {
            get {
                return ResourceManager.GetString("Address_Field_Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode: .
        /// </summary>
        internal static string Address_Field_Post_Code_Label {
            get {
                return ResourceManager.GetString("Address_Field_Post_Code_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State: .
        /// </summary>
        internal static string Address_Field_State_Label {
            get {
                return ResourceManager.GetString("Address_Field_State_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .
        /// </summary>
        internal static string Boolean_No_Label {
            get {
                return ResourceManager.GetString("Boolean_No_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Boolean_Yes_Label {
            get {
                return ResourceManager.GetString("Boolean_Yes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipe choice field.
        /// </summary>
        internal static string CheckBox_Multiple_Choice_Text {
            get {
                return ResourceManager.GetString("CheckBox_Multiple_Choice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day    -    Month  -  Year.
        /// </summary>
        internal static string Date_Structure {
            get {
                return ResourceManager.GetString("Date_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}?userid={2}&amp;segment={3}.
        /// </summary>
        internal static string File_Service_Url_Template {
            get {
                return ResourceManager.GetString("File_Service_Url_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By Evado UniFORM.
        /// </summary>
        internal static string Footer_Text {
            get {
                return ResourceManager.GetString("Footer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        internal static string Html_Url_Field_title {
            get {
                return ResourceManager.GetString("Html_Url_Field_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string Html_Url_Title_Field_Title {
            get {
                return ResourceManager.GetString("Html_Url_Title_Field_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Image_Clear {
            get {
                return ResourceManager.GetString("Image_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete:  .
        /// </summary>
        internal static string Image_Delete_Field_Title {
            get {
                return ResourceManager.GetString("Image_Delete_Field_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:  .
        /// </summary>
        internal static string Image_Title_Field_Title {
            get {
                return ResourceManager.GetString("Image_Title_Field_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: .
        /// </summary>
        internal static string Message_Label {
            get {
                return ResourceManager.GetString("Message_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Month_APR {
            get {
                return ResourceManager.GetString("Month_APR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string Month_AUG {
            get {
                return ResourceManager.GetString("Month_AUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Month_DEC {
            get {
                return ResourceManager.GetString("Month_DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string Month_FEB {
            get {
                return ResourceManager.GetString("Month_FEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string Month_JAN {
            get {
                return ResourceManager.GetString("Month_JAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string Month_JUL {
            get {
                return ResourceManager.GetString("Month_JUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string Month_JUN {
            get {
                return ResourceManager.GetString("Month_JUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string Month_MAR {
            get {
                return ResourceManager.GetString("Month_MAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Month_MAY {
            get {
                return ResourceManager.GetString("Month_MAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Month_NOV {
            get {
                return ResourceManager.GetString("Month_NOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string Month_OCT {
            get {
                return ResourceManager.GetString("Month_OCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Month_SEP {
            get {
                return ResourceManager.GetString("Month_SEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family:.
        /// </summary>
        internal static string Name_Field_Family_Name_Label {
            get {
                return ResourceManager.GetString("Name_Field_Family_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First:.
        /// </summary>
        internal static string Name_Field_First_Name_Label {
            get {
                return ResourceManager.GetString("Name_Field_First_Name_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Needed.
        /// </summary>
        internal static string Page_Message_Action_Group_Title {
            get {
                return ResourceManager.GetString("Page_Message_Action_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Page_Message_Error_Group_Title {
            get {
                return ResourceManager.GetString("Page_Message_Error_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Page_Message_Group_Title {
            get {
                return ResourceManager.GetString("Page_Message_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Page_Message_Warning_Group_Title {
            get {
                return ResourceManager.GetString("Page_Message_Warning_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No option is selected.
        /// </summary>
        internal static string Radio_Button_Not_Selected {
            get {
                return ResourceManager.GetString("Radio_Button_Not_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Signature_Clear {
            get {
                return ResourceManager.GetString("Signature_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp.
        /// </summary>
        internal static string Table_Row_DateStamp {
            get {
                return ResourceManager.GetString("Table_Row_DateStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours   :  Minutes  :  Seconds.
        /// </summary>
        internal static string Time_Structure {
            get {
                return ResourceManager.GetString("Time_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        internal static string User_Login_Title {
            get {
                return ResourceManager.GetString("User_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL has the incorrect video parameters.  .
        /// </summary>
        internal static string Video_Meeting_Parameter_Error_Message {
            get {
                return ResourceManager.GetString("Video_Meeting_Parameter_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video URL:.
        /// </summary>
        internal static string Video_Url_Field_Title {
            get {
                return ResourceManager.GetString("Video_Url_Field_Title", resourceCulture);
            }
        }
    }
}
