//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evado.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EvmLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EvmLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evado.Model.EvmLabels", typeof(EvmLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect UserId or Password was entered. Please re-enter your credentials. .
        /// </summary>
        public static string AUTHENTICATION_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("AUTHENTICATION_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceeded the maximum number of login attempts..
        /// </summary>
        public static string AUTHENTICATION_EXCEEDED_MAX_LOGIN_ATTEMPTS {
            get {
                return ResourceManager.GetString("AUTHENTICATION_EXCEEDED_MAX_LOGIN_ATTEMPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login .
        /// </summary>
        public static string AUTHENTICATION_LOGIN_CMD_TITLE {
            get {
                return ResourceManager.GetString("AUTHENTICATION_LOGIN_CMD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot login as an Evado administrator from this site..
        /// </summary>
        public static string AUTHENTICATION_NOT_ADMIN_SITE {
            get {
                return ResourceManager.GetString("AUTHENTICATION_NOT_ADMIN_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Request..
        /// </summary>
        public static string AUTHENTICATION_REQUEST_LOGIN {
            get {
                return ResourceManager.GetString("AUTHENTICATION_REQUEST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage_Command_Title {
            get {
                return ResourceManager.GetString("HomePage_Command_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON deserialisation failure: .
        /// </summary>
        public static string JSON_DESERIALISATION_ERROR {
            get {
                return ResourceManager.GetString("JSON_DESERIALISATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivityId: .
        /// </summary>
        public static string Label_Activity_Id {
            get {
                return ResourceManager.GetString("Label_Activity_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  by .
        /// </summary>
        public static string Label_by {
            get {
                return ResourceManager.GetString("Label_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  on .
        /// </summary>
        public static string Label_on {
            get {
                return ResourceManager.GetString("Label_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No.
        /// </summary>
        public static string Label_Yes_No {
            get {
                return ResourceManager.GetString("Label_Yes_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Status: {0}.
        /// </summary>
        public static string Meeting_Status_Link_Text {
            get {
                return ResourceManager.GetString("Meeting_Status_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Date: {1}, Time {2}.
        /// </summary>
        public static string Meeting_Subject_Link_Text {
            get {
                return ResourceManager.GetString("Meeting_Subject_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Type: {0}.
        /// </summary>
        public static string Meeting_Type_Link_Text {
            get {
                return ResourceManager.GetString("Meeting_Type_Link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation Type: .
        /// </summary>
        public static string Organisation_Type_Label {
            get {
                return ResourceManager.GetString("Organisation_Type_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &gt; .
        /// </summary>
        public static string Space_Arrow_Right {
            get {
                return ResourceManager.GetString("Space_Arrow_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ) .
        /// </summary>
        public static string Space_Close_Bracket {
            get {
                return ResourceManager.GetString("Space_Close_Bracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string Space_Coma {
            get {
                return ResourceManager.GetString("Space_Coma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        public static string Space_Full_Colon {
            get {
                return ResourceManager.GetString("Space_Full_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string Space_Hypen {
            get {
                return ResourceManager.GetString("Space_Hypen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ( .
        /// </summary>
        public static string Space_Open_Bracket {
            get {
                return ResourceManager.GetString("Space_Open_Bracket", resourceCulture);
            }
        }
    }
}
